-- ============================================================
-- What Would You Pick? — Seed Data
-- Categories + 500+ Questions
-- ============================================================

-- ============================================================
-- CATEGORIES
-- ============================================================
insert into categories (id, name, slug, emoji, order_index) values
  ('cat-money',        'Money',        'money',        '💰', 1),
  ('cat-travel',       'Travel',       'travel',       '✈️', 2),
  ('cat-food',         'Food',         'food',         '🍔', 3),
  ('cat-relationships','Relationships','relationships', '❤️', 4),
  ('cat-career',       'Career',       'career',       '💼', 5),
  ('cat-lifestyle',    'Lifestyle',    'lifestyle',    '🌟', 6),
  ('cat-funny',        'Funny',        'funny',        '😂', 7),
  ('cat-cars',         'Cars',         'cars',         '🚗', 8),
  ('cat-dating',       'Dating',       'dating',       '💘', 9),
  ('cat-movies',       'Movies & TV',  'movies',       '🎬', 10),
  ('cat-sports',       'Sports',       'sports',       '🏆', 11),
  ('cat-luxury',       'Luxury',       'luxury',       '💎', 12),
  ('cat-adventure',    'Adventure',    'adventure',    '🏔️', 13),
  ('cat-weird',        'Weird',        'weird',        '🤯', 14),
  ('cat-family',       'Family',       'family',       '👨‍👩‍👧', 15),
  ('cat-friendship',   'Friendship',   'friendship',   '🤝', 16);

-- ============================================================
-- QUESTIONS
-- ============================================================
insert into questions (text, option_a, option_b, category_id, tags, moderation_status) values

-- ============================================================
-- MONEY (40 questions)
-- ============================================================
('Would you rather get $1 million today or $10,000 every month for life?', '$1 Million Today', '$10k Every Month', 'cat-money', '{"risk_taker","money_minded"}', 'approved'),
('Would you rather have a guaranteed $50k/year salary or a 1-in-10 chance at $1M/year?', 'Guaranteed $50k', '1-in-10 chance at $1M', 'cat-money', '{"risk_taker","practical"}', 'approved'),
('Would you rather never have to pay rent again or never have to pay for food again?', 'Free Rent Forever', 'Free Food Forever', 'cat-money', '{"practical","money_minded"}', 'approved'),
('Would you rather find $500 in old jeans or find a $20 when you expected nothing?', 'Find $500 in jeans', 'Find $20 unexpectedly', 'cat-money', '{"money_minded"}', 'approved'),
('Would you rather earn $200k/year doing work you hate or $60k/year doing work you love?', '$200k doing work I hate', '$60k doing work I love', 'cat-money', '{"career_driven","practical"}', 'approved'),
('Would you rather have $10M in a savings account or own a $10M business?', '$10M in savings', '$10M business', 'cat-money', '{"risk_taker","money_minded"}', 'approved'),
('Would you rather get a $5,000 bonus today or a $500/month raise for the next year?', '$5,000 bonus now', '$500/month raise', 'cat-money', '{"practical","money_minded"}', 'approved'),
('Would you rather inherit $500k at 30 or receive $2,000/month starting now at 22?', '$500k at 30', '$2k/month starting now', 'cat-money', '{"money_minded","planner"}', 'approved'),
('Would you rather lose your wallet with $300 cash or your phone?', 'Lose wallet with $300', 'Lose my phone', 'cat-money', '{"practical"}', 'approved'),
('Would you rather have no car payment or no student loan payment?', 'No car payment', 'No student loans', 'cat-money', '{"practical","money_minded"}', 'approved'),
('Would you rather get paid double your salary for a job you hate or your current salary for a dream job?', 'Double salary, hate the job', 'Current salary, dream job', 'cat-money', '{"career_driven","money_minded"}', 'approved'),
('Would you rather spend $500 on a one-night luxury hotel or $500 on a week-long road trip?', 'One night luxury hotel', 'Week-long road trip', 'cat-money', '{"adventurous","money_minded"}', 'approved'),
('Would you rather have zero debt forever or win $100,000 right now?', 'Zero debt forever', '$100,000 right now', 'cat-money', '{"practical","money_minded"}', 'approved'),
('Would you rather be able to see your bank account balance without anxiety or add $500 to it right now?', 'No financial anxiety', '$500 added right now', 'cat-money', '{"practical"}', 'approved'),
('Would you rather pay off your mortgage early or invest the same money in stocks?', 'Pay off mortgage early', 'Invest in stocks', 'cat-money', '{"practical","risk_taker"}', 'approved'),
('Would you rather have a $1M life insurance policy or $500k in retirement savings?', '$1M life insurance', '$500k retirement savings', 'cat-money', '{"planner","practical"}', 'approved'),
('Would you rather know the exact date of a stock market crash or know winning lottery numbers once?', 'Know market crash date', 'Win the lottery once', 'cat-money', '{"money_minded","risk_taker"}', 'approved'),
('Would you rather get a $10,000 tax refund or owe $0 in taxes?', '$10k tax refund', 'Owe nothing in taxes', 'cat-money', '{"practical","money_minded"}', 'approved'),
('Would you rather negotiate a $15k raise or switch jobs for $20k more?', 'Negotiate a $15k raise', 'Switch jobs for $20k more', 'cat-money', '{"career_driven","risk_taker"}', 'approved'),
('Would you rather have free healthcare for life or free college education for life?', 'Free healthcare for life', 'Free college forever', 'cat-money', '{"practical","planner"}', 'approved'),
('Would you rather have $1M but can only spend it on yourself or $100k you can spend on anything?', '$1M for myself only', '$100k no restrictions', 'cat-money', '{"money_minded","social"}', 'approved'),
('Would you rather retire at 40 with $2M or work until 65 with unlimited wealth?', 'Retire at 40 with $2M', 'Work until 65 unlimited wealth', 'cat-money', '{"planner","money_minded"}', 'approved'),
('Would you rather get paid $1,000 to sit in silence for 24 hours or work a normal 8-hour shift?', '$1,000 for 24 hours silence', 'Normal 8-hour shift', 'cat-money', '{"practical","spontaneous"}', 'approved'),
('Would you rather have a free car for life but it''s always a 10-year-old model, or buy any car you want?', 'Free car, always older model', 'Buy any car I want', 'cat-money', '{"practical","cars"}', 'approved'),
('Would you rather have $50k in credit card debt wiped or have your credit score jump to 800?', '$50k debt wiped', 'Credit score jumps to 800', 'cat-money', '{"practical","money_minded"}', 'approved'),
('Would you rather own a rental property that pays $2k/month or have your primary home fully paid off?', 'Rental property at $2k/month', 'Primary home fully paid off', 'cat-money', '{"money_minded","planner"}', 'approved'),
('Would you rather have a best friend who is a financial advisor or a doctor?', 'Best friend is a financial advisor', 'Best friend is a doctor', 'cat-money', '{"practical","friendship"}', 'approved'),
('Would you rather have your emergency fund fully stocked or your vacation fund filled?', 'Emergency fund fully stocked', 'Vacation fund filled', 'cat-money', '{"practical","planner"}', 'approved'),
('Would you rather earn money online from home or have a high-paying corporate job with benefits?', 'Earn online from home', 'High-paying corporate job', 'cat-money', '{"career_driven","practical"}', 'approved'),
('Would you rather have all your subscriptions paid for life or all your groceries paid for life?', 'All subscriptions free forever', 'All groceries free forever', 'cat-money', '{"practical","money_minded"}', 'approved'),
('Would you rather have $500k to invest in real estate or $500k to start a business?', '$500k in real estate', '$500k to start a business', 'cat-money', '{"money_minded","risk_taker"}', 'approved'),
('Would you rather get a tax-free $1M inheritance or win a $2M lottery (taxed at 40%)?', '$1M tax-free inheritance', '$2M lottery after taxes', 'cat-money', '{"practical","money_minded"}', 'approved'),
('Would you rather get a $50 gift card every week forever or a $10,000 check today?', '$50 gift card weekly forever', '$10,000 today', 'cat-money', '{"practical","money_minded"}', 'approved'),
('Would you rather have passive income of $3k/month from investments or a stable job at $80k/year?', '$3k/month passive income', '$80k/year stable job', 'cat-money', '{"money_minded","planner"}', 'approved'),
('Would you rather negotiate a car price down by $3,000 or get 3 years of free oil changes?', 'Negotiate $3,000 off', '3 years free oil changes', 'cat-money', '{"practical","money_minded"}', 'approved'),
('Would you rather have a financial planner manage your money or learn to do it yourself?', 'Financial planner', 'Learn to manage it myself', 'cat-money', '{"practical","career_driven"}', 'approved'),
('Would you rather invest $10k in crypto or $10k in an index fund?', 'Invest in crypto', 'Invest in index fund', 'cat-money', '{"risk_taker","money_minded"}', 'approved'),
('Would you rather have a $5,000 shopping spree at any store or a 5-night all-inclusive vacation?', '$5,000 shopping spree', '5-night all-inclusive vacation', 'cat-money', '{"lifestyle","adventurous"}', 'approved'),
('Would you rather live paycheck to paycheck in a great city or have savings in a boring town?', 'Paycheck to paycheck, great city', 'Savings in a boring town', 'cat-money', '{"lifestyle","practical"}', 'approved'),
('Would you rather spend $200 on concert tickets or save that $200?', 'Buy concert tickets', 'Save the $200', 'cat-money', '{"practical","lifestyle"}', 'approved'),

-- ============================================================
-- TRAVEL (35 questions)
-- ============================================================
('Would you rather travel the world for 1 year for free or own your dream home?', 'Travel the world free for 1 year', 'Own my dream home', 'cat-travel', '{"adventurous","lifestyle"}', 'approved'),
('Would you rather explore Europe or Southeast Asia on your next vacation?', 'Explore Europe', 'Explore Southeast Asia', 'cat-travel', '{"adventurous","lifestyle"}', 'approved'),
('Would you rather fly first class once a year or fly economy and travel 4x more?', 'Fly first class once', 'Economy but travel 4x more', 'cat-travel', '{"adventurous","practical"}', 'approved'),
('Would you rather live in New York City or Los Angeles?', 'New York City', 'Los Angeles', 'cat-travel', '{"lifestyle","adventurous"}', 'approved'),
('Would you rather visit Paris for 3 days or Tokyo for 3 days?', 'Paris for 3 days', 'Tokyo for 3 days', 'cat-travel', '{"adventurous"}', 'approved'),
('Would you rather travel solo or always travel with someone?', 'Travel solo', 'Always travel with someone', 'cat-travel', '{"adventurous","social"}', 'approved'),
('Would you rather go on a luxury cruise or a backpacking adventure?', 'Luxury cruise', 'Backpacking adventure', 'cat-travel', '{"adventurous","lifestyle"}', 'approved'),
('Would you rather spend a week in Hawaii or a week in the Maldives?', 'Hawaii for a week', 'Maldives for a week', 'cat-travel', '{"adventurous","luxury"}', 'approved'),
('Would you rather live abroad for 5 years or stay in the US your whole life?', 'Live abroad for 5 years', 'Stay in the US forever', 'cat-travel', '{"adventurous","practical"}', 'approved'),
('Would you rather road trip across the US or fly internationally?', 'Road trip across the US', 'Fly internationally', 'cat-travel', '{"adventurous"}', 'approved'),
('Would you rather visit every state in the US or visit 20 different countries?', 'Visit every US state', 'Visit 20 countries', 'cat-travel', '{"adventurous"}', 'approved'),
('Would you rather have a window seat or an aisle seat on a long flight?', 'Window seat', 'Aisle seat', 'cat-travel', '{"practical"}', 'approved'),
('Would you rather explore a new city every weekend or travel less but go to amazing destinations?', 'New city every weekend', 'Fewer but amazing destinations', 'cat-travel', '{"adventurous","practical"}', 'approved'),
('Would you rather vacation at a beach resort or a mountain cabin?', 'Beach resort', 'Mountain cabin', 'cat-travel', '{"adventurous","lifestyle"}', 'approved'),
('Would you rather take a 2-week trip to Africa or a 2-week trip to South America?', 'Africa for 2 weeks', 'South America for 2 weeks', 'cat-travel', '{"adventurous"}', 'approved'),
('Would you rather see the Northern Lights in Iceland or watch the sunset in Santorini?', 'Northern Lights in Iceland', 'Sunset in Santorini', 'cat-travel', '{"adventurous","romantic"}', 'approved'),
('Would you rather stay in an overwater bungalow or a treehouse in the jungle?', 'Overwater bungalow', 'Jungle treehouse', 'cat-travel', '{"adventurous","luxury"}', 'approved'),
('Would you rather travel with unlimited budget but only 3 days, or travel for 3 months on $3,000?', 'Unlimited budget, 3 days', '3 months on $3,000', 'cat-travel', '{"adventurous","practical"}', 'approved'),
('Would you rather visit Disney World or Universal Studios?', 'Disney World', 'Universal Studios', 'cat-travel', '{"fun","family"}', 'approved'),
('Would you rather spend a week in the Swiss Alps or the Italian Amalfi Coast?', 'Swiss Alps', 'Amalfi Coast', 'cat-travel', '{"adventurous","luxury"}', 'approved'),
('Would you rather live in Miami or Chicago?', 'Miami', 'Chicago', 'cat-travel', '{"lifestyle"}', 'approved'),
('Would you rather explore ancient ruins in Egypt or hike Machu Picchu in Peru?', 'Ancient ruins in Egypt', 'Machu Picchu in Peru', 'cat-travel', '{"adventurous","thrill_seeker"}', 'approved'),
('Would you rather take a spontaneous trip with 24 hours notice or plan everything months ahead?', 'Spontaneous 24-hour notice trip', 'Plan everything months ahead', 'cat-travel', '{"spontaneous","planner"}', 'approved'),
('Would you rather visit every continent or deeply explore one country for years?', 'Visit every continent', 'Deeply explore one country', 'cat-travel', '{"adventurous"}', 'approved'),
('Would you rather do a safari in Kenya or a cultural trip to Japan?', 'Safari in Kenya', 'Cultural trip to Japan', 'cat-travel', '{"adventurous"}', 'approved'),
('Would you rather travel in a camper van for a month or stay in 5-star hotels for a week?', 'Camper van for a month', '5-star hotels for a week', 'cat-travel', '{"adventurous","luxury"}', 'approved'),
('Would you rather live in Austin, Texas or Nashville, Tennessee?', 'Austin, Texas', 'Nashville, Tennessee', 'cat-travel', '{"lifestyle"}', 'approved'),
('Would you rather take a cruise to Alaska or a cruise to the Caribbean?', 'Alaska cruise', 'Caribbean cruise', 'cat-travel', '{"adventurous"}', 'approved'),
('Would you rather work remotely from Bali for a year or from Portugal for a year?', 'Remote work from Bali', 'Remote work from Portugal', 'cat-travel', '{"adventurous","career_driven"}', 'approved'),
('Would you rather visit Las Vegas for a wild weekend or a quiet trip to Sedona, AZ?', 'Las Vegas wild weekend', 'Quiet trip to Sedona', 'cat-travel', '{"spontaneous","practical"}', 'approved'),
('Would you rather spend a summer in Europe or a winter in Southeast Asia?', 'Summer in Europe', 'Winter in Southeast Asia', 'cat-travel', '{"adventurous","lifestyle"}', 'approved'),
('Would you rather take a cooking class in Italy or a cooking class in Thailand?', 'Cooking class in Italy', 'Cooking class in Thailand', 'cat-travel', '{"adventurous","foodie"}', 'approved'),
('Would you rather swim with dolphins or go cage diving with sharks?', 'Swim with dolphins', 'Cage dive with sharks', 'cat-travel', '{"thrill_seeker","adventurous"}', 'approved'),
('Would you rather sleep under the stars in the Sahara Desert or in an ice hotel in Norway?', 'Sleep under stars in Sahara', 'Ice hotel in Norway', 'cat-travel', '{"adventurous","thrill_seeker"}', 'approved'),
('Would you rather spend a week in NYC or a week in San Francisco?', 'New York City for a week', 'San Francisco for a week', 'cat-travel', '{"lifestyle","adventurous"}', 'approved'),

-- ============================================================
-- FOOD (35 questions)
-- ============================================================
('Would you rather eat pizza every day for a year or never eat pizza again?', 'Pizza every day for a year', 'Never eat pizza again', 'cat-food', '{"foodie"}', 'approved'),
('Would you rather have a personal chef or eat at Michelin-star restaurants for free?', 'Personal chef', 'Free Michelin-star dining', 'cat-food', '{"foodie","luxury"}', 'approved'),
('Would you rather give up coffee for life or give up alcohol for life?', 'Give up coffee forever', 'Give up alcohol forever', 'cat-food', '{"lifestyle","practical"}', 'approved'),
('Would you rather eat only American food forever or eat only food from a different country?', 'American food only', 'Food from one other country', 'cat-food', '{"foodie","adventurous"}', 'approved'),
('Would you rather eat the best burger you''ve ever had or the best sushi you''ve ever had?', 'Best burger ever', 'Best sushi ever', 'cat-food', '{"foodie"}', 'approved'),
('Would you rather be a great cook or always know the best restaurants nearby?', 'Be a great cook', 'Always know the best restaurant', 'cat-food', '{"foodie","practical"}', 'approved'),
('Would you rather eat spicy food every meal or eat bland food every meal?', 'Spicy food every meal', 'Bland food every meal', 'cat-food', '{"foodie","thrill_seeker"}', 'approved'),
('Would you rather eat breakfast for dinner or dinner for breakfast?', 'Breakfast for dinner', 'Dinner for breakfast', 'cat-food', '{"foodie","spontaneous"}', 'approved'),
('Would you rather eat at a food truck with amazing food or a fancy restaurant with okay food?', 'Amazing food truck', 'Fancy restaurant with okay food', 'cat-food', '{"foodie","practical"}', 'approved'),
('Would you rather have unlimited sushi or unlimited tacos?', 'Unlimited sushi', 'Unlimited tacos', 'cat-food', '{"foodie"}', 'approved'),
('Would you rather eat a steak every week or never eat red meat again?', 'Steak every week', 'Never eat red meat again', 'cat-food', '{"foodie","practical"}', 'approved'),
('Would you rather eat only sweet food for a week or only savory food for a week?', 'Only sweet for a week', 'Only savory for a week', 'cat-food', '{"foodie"}', 'approved'),
('Would you rather cook a meal from scratch every day or meal prep every Sunday?', 'Cook fresh daily', 'Meal prep every Sunday', 'cat-food', '{"practical","foodie"}', 'approved'),
('Would you rather eat at your favorite restaurant every week or try a new restaurant every week?', 'Favorite restaurant weekly', 'New restaurant weekly', 'cat-food', '{"foodie","adventurous"}', 'approved'),
('Would you rather never eat junk food again or give up your favorite healthy food?', 'Never eat junk food again', 'Give up my favorite healthy food', 'cat-food', '{"lifestyle","practical"}', 'approved'),
('Would you rather eat wings with sauce or dry rub wings?', 'Wings with sauce', 'Dry rub wings', 'cat-food', '{"foodie"}', 'approved'),
('Would you rather have an endless supply of your favorite snack or an endless supply of your favorite drink?', 'Endless favorite snack', 'Endless favorite drink', 'cat-food', '{"foodie"}', 'approved'),
('Would you rather eat a 5-course meal alone or a simple sandwich with great company?', '5-course meal alone', 'Simple sandwich with great company', 'cat-food', '{"social","foodie"}', 'approved'),
('Would you rather have the ability to taste flavors more intensely or smell aromas more vividly?', 'Taste flavors more intensely', 'Smell aromas more vividly', 'cat-food', '{"foodie"}', 'approved'),
('Would you rather eat fast food for a week or go vegan for a week?', 'Fast food for a week', 'Vegan for a week', 'cat-food', '{"foodie","lifestyle"}', 'approved'),
('Would you rather eat the world''s best ice cream or the world''s best chocolate?', 'World''s best ice cream', 'World''s best chocolate', 'cat-food', '{"foodie"}', 'approved'),
('Would you rather eat at a local hole-in-the-wall or a popular Instagram-famous spot?', 'Local hole-in-the-wall', 'Instagram-famous spot', 'cat-food', '{"foodie","social"}', 'approved'),
('Would you rather have homemade cookies or a professional bakery pastry?', 'Homemade cookies', 'Professional bakery pastry', 'cat-food', '{"foodie"}', 'approved'),
('Would you rather eat Korean BBQ or Japanese ramen on a cold night?', 'Korean BBQ', 'Japanese ramen', 'cat-food', '{"foodie"}', 'approved'),
('Would you rather eat lobster every day for a month or never eat seafood again?', 'Lobster every day for a month', 'Never eat seafood again', 'cat-food', '{"foodie"}', 'approved'),
('Would you rather host a dinner party for 10 or go out to a restaurant with close friends?', 'Host a dinner party', 'Go out with close friends', 'cat-food', '{"social","foodie"}', 'approved'),
('Would you rather eat only organic food forever or eat whatever you want?', 'Only organic food forever', 'Eat whatever I want', 'cat-food', '{"lifestyle","practical"}', 'approved'),
('Would you rather eat at a steakhouse or a seafood restaurant for a special occasion?', 'Steakhouse', 'Seafood restaurant', 'cat-food', '{"foodie","luxury"}', 'approved'),
('Would you rather wake up to the smell of fresh bacon or fresh cinnamon rolls?', 'Fresh bacon', 'Cinnamon rolls', 'cat-food', '{"foodie"}', 'approved'),
('Would you rather drink a green smoothie every morning or eat a hearty breakfast?', 'Green smoothie every morning', 'Hearty breakfast', 'cat-food', '{"lifestyle","foodie"}', 'approved'),
('Would you rather eat a giant burrito or a large deep-dish pizza right now?', 'Giant burrito', 'Deep-dish pizza', 'cat-food', '{"foodie"}', 'approved'),
('Would you rather eat at an authentic Mexican taqueria or a gourmet French bistro?', 'Authentic Mexican taqueria', 'Gourmet French bistro', 'cat-food', '{"foodie","adventurous"}', 'approved'),
('Would you rather have a lifetime supply of your favorite candy or your favorite soda?', 'Lifetime supply of favorite candy', 'Lifetime supply of favorite soda', 'cat-food', '{"foodie"}', 'approved'),
('Would you rather eat only comfort food or only healthy food for a year?', 'Only comfort food for a year', 'Only healthy food for a year', 'cat-food', '{"lifestyle","practical"}', 'approved'),
('Would you rather eat a BBQ cookout meal or a Thanksgiving-style feast?', 'BBQ cookout meal', 'Thanksgiving-style feast', 'cat-food', '{"foodie","family"}', 'approved'),

-- ============================================================
-- RELATIONSHIPS (35 questions)
-- ============================================================
('Would you rather be in a long-distance relationship with the perfect person or close by but an imperfect match?', 'Long-distance, perfect person', 'Close by, imperfect match', 'cat-relationships', '{"romantic","practical"}', 'approved'),
('Would you rather have your partner be your best friend or keep them as a romantic mystery?', 'Partner as best friend', 'Keep the romantic mystery', 'cat-relationships', '{"romantic","social"}', 'approved'),
('Would you rather be with someone who challenges you intellectually or someone who makes you feel completely at ease?', 'Intellectually challenging', 'Completely at ease', 'cat-relationships', '{"romantic","practical"}', 'approved'),
('Would you rather know your partner''s entire past or keep some mystery?', 'Know their entire past', 'Keep some mystery', 'cat-relationships', '{"romantic","practical"}', 'approved'),
('Would you rather be with someone who is adventurous but unreliable or safe but boring?', 'Adventurous but unreliable', 'Safe but boring', 'cat-relationships', '{"romantic","adventurous"}', 'approved'),
('Would you rather have a relationship with no arguments ever or one where you argue but always make up?', 'No arguments ever', 'Arguments with great makeups', 'cat-relationships', '{"romantic","practical"}', 'approved'),
('Would you rather receive thoughtful gifts or thoughtful words from your partner?', 'Thoughtful gifts', 'Thoughtful words', 'cat-relationships', '{"romantic"}', 'approved'),
('Would you rather be in a relationship with a homebody or a social butterfly?', 'Homebody partner', 'Social butterfly partner', 'cat-relationships', '{"romantic","social"}', 'approved'),
('Would you rather fall in love fast and hard or slow and steady?', 'Fall in love fast and hard', 'Fall in love slow and steady', 'cat-relationships', '{"romantic","spontaneous"}', 'approved'),
('Would you rather be with someone who is extremely funny or extremely intelligent?', 'Extremely funny partner', 'Extremely intelligent partner', 'cat-relationships', '{"romantic"}', 'approved'),
('Would you rather know exactly when you will meet your soulmate or not know and be surprised?', 'Know exactly when', 'Be surprised', 'cat-relationships', '{"romantic","planner"}', 'approved'),
('Would you rather have a perfect marriage for 10 years or a good marriage for 50 years?', 'Perfect marriage for 10 years', 'Good marriage for 50 years', 'cat-relationships', '{"romantic","planner"}', 'approved'),
('Would you rather share every password with your partner or have complete digital privacy?', 'Share every password', 'Complete digital privacy', 'cat-relationships', '{"romantic","practical"}', 'approved'),
('Would you rather have a partner who is great with money or great with emotions?', 'Great with money', 'Great with emotions', 'cat-relationships', '{"romantic","practical"}', 'approved'),
('Would you rather spend Friday nights in with your partner or go out every weekend?', 'Friday nights in', 'Go out every weekend', 'cat-relationships', '{"romantic","lifestyle"}', 'approved'),
('Would you rather have a partner who is a fantastic cook or a great listener?', 'Fantastic cook partner', 'Great listener partner', 'cat-relationships', '{"romantic","social"}', 'approved'),
('Would you rather get married young and grow together or marry late when you both are established?', 'Marry young, grow together', 'Marry late, both established', 'cat-relationships', '{"romantic","planner"}', 'approved'),
('Would you rather have a partner who surprises you often or one you can always predict?', 'Partner who surprises me', 'Partner I can predict', 'cat-relationships', '{"romantic","spontaneous"}', 'approved'),
('Would you rather be the breadwinner or have an equal split in your relationship?', 'Be the breadwinner', 'Equal split', 'cat-relationships', '{"practical","romantic"}', 'approved'),
('Would you rather have a big romantic wedding or a small intimate ceremony?', 'Big romantic wedding', 'Small intimate ceremony', 'cat-relationships', '{"romantic","lifestyle"}', 'approved'),
('Would you rather have a partner who is ambitious and always busy or relaxed but present?', 'Ambitious but busy partner', 'Relaxed but always present', 'cat-relationships', '{"romantic","practical"}', 'approved'),
('Would you rather know your partner will never cheat or be told they already did once but never will again?', 'Know they will never cheat', 'Once but never again', 'cat-relationships', '{"romantic","practical"}', 'approved'),
('Would you rather have a partner who is your complete opposite or your mirror image?', 'Complete opposite', 'Mirror image', 'cat-relationships', '{"romantic"}', 'approved'),
('Would you rather live together before marriage or wait until after?', 'Live together before marriage', 'Wait until after marriage', 'cat-relationships', '{"romantic","planner"}', 'approved'),
('Would you rather have a partner who loves your family or a partner who is your whole world?', 'Partner who loves my family', 'Partner who is my whole world', 'cat-relationships', '{"romantic","family"}', 'approved'),
('Would you rather be deeply loved by one person or admired by many?', 'Deeply loved by one person', 'Admired by many', 'cat-relationships', '{"romantic","social"}', 'approved'),
('Would you rather have a romantic partner who is also your business partner or keep those completely separate?', 'Also my business partner', 'Keep completely separate', 'cat-relationships', '{"romantic","career_driven"}', 'approved'),
('Would you rather have a partner who always tells you the truth even when it hurts or white lies to protect you?', 'Always the truth', 'White lies to protect me', 'cat-relationships', '{"romantic","practical"}', 'approved'),
('Would you rather be in a relationship with a night owl or an early bird?', 'Night owl partner', 'Early bird partner', 'cat-relationships', '{"lifestyle","romantic"}', 'approved'),
('Would you rather have a partner who values experiences over things or things over experiences?', 'Values experiences', 'Values things', 'cat-relationships', '{"romantic","lifestyle"}', 'approved'),
('Would you rather have a partner who makes you laugh every day or makes you feel safe every day?', 'Makes me laugh every day', 'Makes me feel safe every day', 'cat-relationships', '{"romantic"}', 'approved'),
('Would you rather be with someone who loves PDA or someone who is private?', 'Loves PDA', 'Keeps it private', 'cat-relationships', '{"romantic","social"}', 'approved'),
('Would you rather have a partner who plans every date or always leaves it spontaneous?', 'Plans every date', 'Always spontaneous', 'cat-relationships', '{"romantic","planner"}', 'approved'),
('Would you rather have your partner be your cheerleader or your critic who makes you better?', 'My cheerleader', 'My critic who makes me better', 'cat-relationships', '{"romantic","career_driven"}', 'approved'),
('Would you rather be loved for who you are now or loved for who you could become?', 'Loved for who I am now', 'Loved for who I could become', 'cat-relationships', '{"romantic"}', 'approved'),

-- ============================================================
-- CAREER (30 questions)
-- ============================================================
('Would you rather be your own boss with uncertain income or work for someone with guaranteed pay?', 'Be my own boss', 'Work for someone, guaranteed pay', 'cat-career', '{"career_driven","risk_taker"}', 'approved'),
('Would you rather work 4 days a week for less money or 5 days for more?', 'Work 4 days, earn less', 'Work 5 days, earn more', 'cat-career', '{"practical","lifestyle"}', 'approved'),
('Would you rather have a job title that impresses everyone or a job that actually fulfills you?', 'Impressive job title', 'Fulfilling job', 'cat-career', '{"career_driven","lifestyle"}', 'approved'),
('Would you rather work remotely forever or have a great office environment to go to?', 'Remote forever', 'Great office environment', 'cat-career', '{"career_driven","lifestyle"}', 'approved'),
('Would you rather have a job that pays $200k with no work-life balance or $80k with total balance?', '$200k no work-life balance', '$80k total balance', 'cat-career', '{"career_driven","lifestyle"}', 'approved'),
('Would you rather fail at your dream career or succeed at a career you hate?', 'Fail at dream career', 'Succeed at career I hate', 'cat-career', '{"career_driven","risk_taker"}', 'approved'),
('Would you rather have a mentor who built a $100M company or a mentor who is happy and fulfilled?', 'Mentor who built $100M company', 'Mentor who is happy and fulfilled', 'cat-career', '{"career_driven","lifestyle"}', 'approved'),
('Would you rather get promoted quickly but work for a toxic company or stay longer at a great workplace?', 'Quick promotion, toxic company', 'Longer at a great workplace', 'cat-career', '{"career_driven","practical"}', 'approved'),
('Would you rather know your career path perfectly mapped out or discover it as you go?', 'Perfectly mapped out', 'Discover as I go', 'cat-career', '{"planner","spontaneous"}', 'approved'),
('Would you rather give a speech to 10,000 people or have a 1-on-1 meeting with the CEO of Google?', 'Speech to 10,000 people', '1-on-1 with Google CEO', 'cat-career', '{"career_driven","social"}', 'approved'),
('Would you rather switch careers every 5 years or master one career over 30 years?', 'Switch every 5 years', 'Master one career for 30 years', 'cat-career', '{"career_driven","adventurous"}', 'approved'),
('Would you rather work at a startup with equity or a Fortune 500 with stability?', 'Startup with equity', 'Fortune 500 with stability', 'cat-career', '{"risk_taker","practical"}', 'approved'),
('Would you rather take a job you love that barely covers bills or a job you tolerate that builds wealth?', 'Job I love, barely covers bills', 'Job I tolerate, builds wealth', 'cat-career', '{"career_driven","money_minded"}', 'approved'),
('Would you rather be known as the smartest person in the room or the hardest worker?', 'Smartest in the room', 'Hardest worker', 'cat-career', '{"career_driven"}', 'approved'),
('Would you rather work in tech or healthcare?', 'Work in tech', 'Work in healthcare', 'cat-career', '{"career_driven"}', 'approved'),
('Would you rather be fired from a job you love or quit a job you hate?', 'Fired from a job I love', 'Quit a job I hate', 'cat-career', '{"career_driven","practical"}', 'approved'),
('Would you rather have a job that travels a lot or one that keeps you home?', 'Job that travels a lot', 'Job that keeps me home', 'cat-career', '{"adventurous","lifestyle"}', 'approved'),
('Would you rather have a great resume or a great network?', 'Great resume', 'Great network', 'cat-career', '{"career_driven","social"}', 'approved'),
('Would you rather start your career over at 22 knowing what you know now or stay on your current path?', 'Start over at 22', 'Stay on current path', 'cat-career', '{"career_driven","planner"}', 'approved'),
('Would you rather work in a creative field or a technical field?', 'Creative field', 'Technical field', 'cat-career', '{"career_driven"}', 'approved'),
('Would you rather have a job that no one understands but you love it, or a job everyone respects but you hate?', 'No one understands, I love it', 'Everyone respects, I hate it', 'cat-career', '{"career_driven","social"}', 'approved'),
('Would you rather have 10 years of experience in one company or the same time across 5 companies?', '10 years one company', '5 companies over 10 years', 'cat-career', '{"career_driven","practical"}', 'approved'),
('Would you rather have perfect work-life balance with average pay or high pay with no balance?', 'Perfect balance, average pay', 'High pay, no balance', 'cat-career', '{"lifestyle","money_minded"}', 'approved'),
('Would you rather work for Elon Musk or Jeff Bezos?', 'Work for Elon Musk', 'Work for Jeff Bezos', 'cat-career', '{"career_driven"}', 'approved'),
('Would you rather build a product used by millions or lead a team of 50 exceptional people?', 'Product used by millions', 'Lead a team of 50', 'cat-career', '{"career_driven","social"}', 'approved'),
('Would you rather be promoted to CEO at 35 or retire comfortably at 45?', 'CEO at 35', 'Retire at 45', 'cat-career', '{"career_driven","money_minded"}', 'approved'),
('Would you rather work in New York City or work remotely from anywhere?', 'Work in New York City', 'Work remotely from anywhere', 'cat-career', '{"career_driven","adventurous"}', 'approved'),
('Would you rather take 3 months unpaid leave to start something new or stay in your current job safely?', '3 months unpaid to start something', 'Stay in current job safely', 'cat-career', '{"risk_taker","career_driven"}', 'approved'),
('Would you rather become a thought leader in your field or a wealthy generalist?', 'Thought leader in my field', 'Wealthy generalist', 'cat-career', '{"career_driven","money_minded"}', 'approved'),
('Would you rather work on something you believe in for less money or something meaningless for more?', 'Believe in it, earn less', 'Meaningless but earn more', 'cat-career', '{"career_driven","money_minded"}', 'approved'),

-- ============================================================
-- DATING (25 questions)
-- ============================================================
('Would you rather date someone who is extremely attractive but average personality, or average looks but magnetic personality?', 'Extremely attractive, average personality', 'Average looks, magnetic personality', 'cat-dating', '{"romantic"}', 'approved'),
('Would you rather be the one who cares more or the one who cares less in a relationship?', 'Care more', 'Care less', 'cat-dating', '{"romantic","practical"}', 'approved'),
('Would you rather go on a first date to a fancy restaurant or a casual coffee shop?', 'Fancy restaurant', 'Casual coffee shop', 'cat-dating', '{"romantic","practical"}', 'approved'),
('Would you rather date someone you met on an app or someone you met in real life?', 'Met on an app', 'Met in real life', 'cat-dating', '{"romantic","social"}', 'approved'),
('Would you rather date someone who has dated a lot or someone with very little dating experience?', 'Dated a lot', 'Very little experience', 'cat-dating', '{"romantic"}', 'approved'),
('Would you rather date someone who is always positive or someone who is honest even when it''s negative?', 'Always positive', 'Honest even when negative', 'cat-dating', '{"romantic","practical"}', 'approved'),
('Would you rather date someone taller than you or shorter than you?', 'Someone taller', 'Someone shorter', 'cat-dating', '{"romantic"}', 'approved'),
('Would you rather be someone''s first love or their last love?', 'Their first love', 'Their last love', 'cat-dating', '{"romantic"}', 'approved'),
('Would you rather date someone who loves to travel or someone who loves to stay home?', 'Loves to travel', 'Loves to stay home', 'cat-dating', '{"romantic","adventurous"}', 'approved'),
('Would you rather be in a committed relationship at 25 or focus on yourself until 30?', 'Committed relationship at 25', 'Focus on myself until 30', 'cat-dating', '{"romantic","career_driven"}', 'approved'),
('Would you rather date someone who is your best friend first or feel instant romantic chemistry?', 'Best friend first', 'Instant romantic chemistry', 'cat-dating', '{"romantic","social"}', 'approved'),
('Would you rather date someone who has a great sense of humor or great ambition?', 'Great sense of humor', 'Great ambition', 'cat-dating', '{"romantic","career_driven"}', 'approved'),
('Would you rather have your partner be older than you or younger?', 'Partner older than me', 'Partner younger than me', 'cat-dating', '{"romantic"}', 'approved'),
('Would you rather date someone who is family-oriented or career-focused?', 'Family-oriented', 'Career-focused', 'cat-dating', '{"romantic","family"}', 'approved'),
('Would you rather have a partner who loves sports or one who loves the arts?', 'Loves sports', 'Loves the arts', 'cat-dating', '{"romantic","lifestyle"}', 'approved'),
('Would you rather date someone who is always early or always 15 minutes late?', 'Always early', 'Always 15 minutes late', 'cat-dating', '{"romantic","practical"}', 'approved'),
('Would you rather be with someone who makes you a better person or someone who accepts you as you are?', 'Makes me a better person', 'Accepts me as I am', 'cat-dating', '{"romantic"}', 'approved'),
('Would you rather have your partner be your gym partner or your study/work partner?', 'Gym partner', 'Study/work partner', 'cat-dating', '{"romantic","lifestyle"}', 'approved'),
('Would you rather date someone who is low-maintenance or someone who loves to be pampered?', 'Low-maintenance', 'Loves to be pampered', 'cat-dating', '{"romantic","lifestyle"}', 'approved'),
('Would you rather fall in love with someone in 3 months or take 3 years to be sure?', 'Fall in love in 3 months', 'Take 3 years to be sure', 'cat-dating', '{"romantic","planner"}', 'approved'),
('Would you rather have your date plan everything or plan everything yourself?', 'My date plans everything', 'I plan everything', 'cat-dating', '{"romantic","planner"}', 'approved'),
('Would you rather date someone who is obsessed with their career or obsessed with you?', 'Obsessed with their career', 'Obsessed with me', 'cat-dating', '{"romantic","career_driven"}', 'approved'),
('Would you rather have a relationship that starts as a friendship or a passionate whirlwind?', 'Starts as friendship', 'Passionate whirlwind', 'cat-dating', '{"romantic","spontaneous"}', 'approved'),
('Would you rather have someone who sends good morning texts every day or surprises you at your door?', 'Good morning texts every day', 'Surprise at my door', 'cat-dating', '{"romantic","spontaneous"}', 'approved'),
('Would you rather date someone who is obsessed with food or obsessed with fitness?', 'Obsessed with food', 'Obsessed with fitness', 'cat-dating', '{"romantic","lifestyle"}', 'approved'),

-- ============================================================
-- LIFESTYLE (25 questions)
-- ============================================================
('Would you rather wake up at 5am every day and be super productive or sleep in until 9am and feel rested?', 'Wake up at 5am, be productive', 'Sleep until 9am, feel rested', 'cat-lifestyle', '{"practical","lifestyle"}', 'approved'),
('Would you rather live in a big city or a quiet suburb?', 'Big city', 'Quiet suburb', 'cat-lifestyle', '{"lifestyle","practical"}', 'approved'),
('Would you rather have a huge house in a bad neighborhood or a small apartment in an amazing area?', 'Huge house, bad neighborhood', 'Small apartment, amazing area', 'cat-lifestyle', '{"lifestyle","practical"}', 'approved'),
('Would you rather have a perfect body with zero effort or a brilliant mind with zero effort?', 'Perfect body with zero effort', 'Brilliant mind with zero effort', 'cat-lifestyle', '{"lifestyle","practical"}', 'approved'),
('Would you rather live to 120 with average health or 80 with excellent health every day?', 'Live to 120, average health', 'Live to 80, excellent health', 'cat-lifestyle', '{"practical","lifestyle"}', 'approved'),
('Would you rather have a huge social circle or 3 incredibly close friends?', 'Huge social circle', '3 incredibly close friends', 'cat-lifestyle', '{"social","lifestyle"}', 'approved'),
('Would you rather own a dog or a cat?', 'Dog', 'Cat', 'cat-lifestyle', '{"lifestyle"}', 'approved'),
('Would you rather always be overdressed or always be underdressed?', 'Always overdressed', 'Always underdressed', 'cat-lifestyle', '{"lifestyle","social"}', 'approved'),
('Would you rather have a gym at home or a premium gym membership near work?', 'Gym at home', 'Premium gym near work', 'cat-lifestyle', '{"practical","lifestyle"}', 'approved'),
('Would you rather meditate every morning for 20 minutes or work out for 20 minutes?', 'Meditate every morning', 'Work out every morning', 'cat-lifestyle', '{"lifestyle","practical"}', 'approved'),
('Would you rather live in a penthouse apartment or a large house with a backyard?', 'Penthouse apartment', 'Large house with backyard', 'cat-lifestyle', '{"lifestyle","luxury"}', 'approved'),
('Would you rather be the smartest person in the room or the most likeable?', 'Smartest in the room', 'Most likeable', 'cat-lifestyle', '{"social","career_driven"}', 'approved'),
('Would you rather always have clean laundry or always have a clean kitchen?', 'Always clean laundry', 'Always clean kitchen', 'cat-lifestyle', '{"practical"}', 'approved'),
('Would you rather have a fast metabolism or incredible natural energy?', 'Fast metabolism', 'Incredible natural energy', 'cat-lifestyle', '{"lifestyle","practical"}', 'approved'),
('Would you rather binge-watch TV on weekends or spend weekends being active outdoors?', 'Binge-watch TV', 'Active outdoors', 'cat-lifestyle', '{"lifestyle","adventurous"}', 'approved'),
('Would you rather live in a warm climate year-round or experience all 4 seasons?', 'Warm climate year-round', 'All 4 seasons', 'cat-lifestyle', '{"lifestyle"}', 'approved'),
('Would you rather have a morning routine that never changes or a different morning every day?', 'Same morning routine always', 'Different morning every day', 'cat-lifestyle', '{"planner","spontaneous"}', 'approved'),
('Would you rather have perfect sleep every night or never need more than 4 hours?', 'Perfect sleep every night', 'Only need 4 hours', 'cat-lifestyle', '{"practical","lifestyle"}', 'approved'),
('Would you rather spend your Saturday reading books or trying a new outdoor activity?', 'Reading books', 'New outdoor activity', 'cat-lifestyle', '{"lifestyle","adventurous"}', 'approved'),
('Would you rather have a perfectly organized home or a creatively messy one that inspires you?', 'Perfectly organized home', 'Creatively messy, inspiring', 'cat-lifestyle', '{"lifestyle","practical"}', 'approved'),
('Would you rather drive a luxury car or have a driver available anytime?', 'Drive a luxury car', 'Have a driver anytime', 'cat-lifestyle', '{"luxury","lifestyle"}', 'approved'),
('Would you rather have unlimited vacation days or a 3-day work week?', 'Unlimited vacation days', '3-day work week', 'cat-lifestyle', '{"lifestyle","career_driven"}', 'approved'),
('Would you rather spend evenings working on a side project or fully unwinding?', 'Work on a side project', 'Fully unwind every evening', 'cat-lifestyle', '{"career_driven","lifestyle"}', 'approved'),
('Would you rather go to therapy regularly or have a great life coach?', 'Go to therapy regularly', 'Have a great life coach', 'cat-lifestyle', '{"practical","lifestyle"}', 'approved'),
('Would you rather be an early adopter of every new tech or never upgrade until forced?', 'Always first to adopt tech', 'Never upgrade until forced', 'cat-lifestyle', '{"practical","lifestyle"}', 'approved'),

-- ============================================================
-- FUNNY (30 questions)
-- ============================================================
('Would you rather have fingers for toes or toes for fingers?', 'Fingers for toes', 'Toes for fingers', 'cat-funny', '{"weird","spontaneous"}', 'approved'),
('Would you rather smell like bacon all the time or always sound like you''re whispering?', 'Smell like bacon always', 'Always whisper', 'cat-funny', '{"weird","funny"}', 'approved'),
('Would you rather fight 100 duck-sized horses or 1 horse-sized duck?', '100 duck-sized horses', '1 horse-sized duck', 'cat-funny', '{"thrill_seeker","weird"}', 'approved'),
('Would you rather speak every language in the world or play every musical instrument perfectly?', 'Speak every language', 'Play every instrument', 'cat-funny', '{"practical","social"}', 'approved'),
('Would you rather always talk in rhymes or sing everything you say?', 'Always talk in rhymes', 'Sing everything I say', 'cat-funny', '{"spontaneous","weird"}', 'approved'),
('Would you rather have hiccups every time you lie or sneeze every time you think of money?', 'Hiccups when I lie', 'Sneeze when I think of money', 'cat-funny', '{"weird","funny"}', 'approved'),
('Would you rather accidentally call your teacher Mom or call your Mom your teacher''s name?', 'Call teacher Mom', 'Call Mom teacher''s name', 'cat-funny', '{"weird","funny"}', 'approved'),
('Would you rather only eat food that''s already been dropped or food that''s room temperature always?', 'Food that''s been dropped', 'Always room temperature food', 'cat-funny', '{"weird","funny"}', 'approved'),
('Would you rather have the superpower of flight but only 1 mph or invisibility but only while alone?', 'Fly at 1 mph', 'Invisible only when alone', 'cat-funny', '{"weird","funny"}', 'approved'),
('Would you rather live in a world where everyone can read minds or no one has any secrets?', 'Everyone reads minds', 'No one has secrets', 'cat-funny', '{"weird","social"}', 'approved'),
('Would you rather sneeze glitter every time or have a theme song play when you walk into a room?', 'Sneeze glitter', 'Theme song when I walk in', 'cat-funny', '{"spontaneous","weird"}', 'approved'),
('Would you rather only be able to walk sideways or only be able to crawl on all fours?', 'Walk sideways', 'Crawl everywhere', 'cat-funny', '{"weird","funny"}', 'approved'),
('Would you rather have unlimited pizza but it''s always slightly cold or perfect pizza but only once a month?', 'Unlimited slightly cold pizza', 'Perfect pizza once a month', 'cat-funny', '{"foodie","funny"}', 'approved'),
('Would you rather get free food at one restaurant for life but it''s mediocre, or win a Michelin-star dinner once?', 'Free mediocre food for life', 'One Michelin-star dinner', 'cat-funny', '{"foodie","practical"}', 'approved'),
('Would you rather have 3 wishes that all backfire slightly or 1 wish that works perfectly?', '3 wishes that slightly backfire', '1 wish that works perfectly', 'cat-funny', '{"risk_taker","funny"}', 'approved'),
('Would you rather narrate your life in third person or have someone else narrate it for you?', 'Narrate my own life', 'Have someone narrate it', 'cat-funny', '{"weird","spontaneous"}', 'approved'),
('Would you rather always have to give a high-five when greeting someone or always bow?', 'Always high-five', 'Always bow', 'cat-funny', '{"social","funny"}', 'approved'),
('Would you rather know every language but forget your own or keep your language but forget all others?', 'Know every language, forget mine', 'Keep mine, forget all others', 'cat-funny', '{"weird","practical"}', 'approved'),
('Would you rather have your browser history projected on a billboard for 24 hours or read every work email out loud?', 'Browser history on billboard', 'Read all work emails out loud', 'cat-funny', '{"weird","funny"}', 'approved'),
('Would you rather have a pet dinosaur that is friendly but clumsy or a pet dragon you cannot control?', 'Friendly clumsy dinosaur', 'Uncontrollable dragon', 'cat-funny', '{"thrill_seeker","funny"}', 'approved'),
('Would you rather only eat with chopsticks forever or only eat with your hands?', 'Only chopsticks forever', 'Only with my hands', 'cat-funny', '{"weird","funny"}', 'approved'),
('Would you rather your laugh be a total silence or a foghorn?', 'Laugh in total silence', 'Laugh like a foghorn', 'cat-funny', '{"weird","social"}', 'approved'),
('Would you rather win an argument with your boss or win an argument with your parents?', 'Win argument with my boss', 'Win argument with my parents', 'cat-funny', '{"funny","social"}', 'approved'),
('Would you rather have X-ray vision but only see bones or night vision but only at night?', 'X-ray vision (bones only)', 'Night vision (night only)', 'cat-funny', '{"weird","practical"}', 'approved'),
('Would you rather speak your mind every time with no filter or never be able to express your opinion?', 'Always speak my mind, no filter', 'Never express an opinion', 'cat-funny', '{"social","weird"}', 'approved'),
('Would you rather hiccup every time you hear the word "the" or blink three times every time you swallow?', 'Hiccup at "the"', 'Blink three times when swallowing', 'cat-funny', '{"weird","funny"}', 'approved'),
('Would you rather have a closet that automatically organizes your clothes or a fridge that restocks itself?', 'Auto-organizing closet', 'Self-restocking fridge', 'cat-funny', '{"practical","funny"}', 'approved'),
('Would you rather age backwards from 50 to 0 or age normally but live to 200?', 'Age backwards from 50', 'Live normally to 200', 'cat-funny', '{"weird","lifestyle"}', 'approved'),
('Would you rather always forget names or always forget faces?', 'Forget names', 'Forget faces', 'cat-funny', '{"social","funny"}', 'approved'),
('Would you rather only watch movies with no sound or only listen to movies with no picture?', 'Movies with no sound', 'Movies with no picture', 'cat-funny', '{"funny","weird"}', 'approved'),

-- ============================================================
-- CARS (25 questions)
-- ============================================================
('Would you rather drive a Ferrari for 1 year or own a Toyota Camry for 10 years?', 'Ferrari for 1 year', 'Toyota Camry for 10 years', 'cat-cars', '{"practical","luxury"}', 'approved'),
('Would you rather have a self-driving car or always drive yourself?', 'Self-driving car', 'Always drive myself', 'cat-cars', '{"practical","lifestyle"}', 'approved'),
('Would you rather drive a Tesla Model S or a Porsche 911?', 'Tesla Model S', 'Porsche 911', 'cat-cars', '{"luxury","lifestyle"}', 'approved'),
('Would you rather drive a brand-new economy car or a 5-year-old luxury car?', 'Brand-new economy car', '5-year-old luxury car', 'cat-cars', '{"practical","luxury"}', 'approved'),
('Would you rather own a pickup truck or an SUV?', 'Pickup truck', 'SUV', 'cat-cars', '{"practical","lifestyle"}', 'approved'),
('Would you rather drive fast on empty roads forever or drive slow but always find parking?', 'Drive fast on empty roads', 'Drive slow, always find parking', 'cat-cars', '{"thrill_seeker","practical"}', 'approved'),
('Would you rather own a Lamborghini Urus or a Range Rover?', 'Lamborghini Urus', 'Range Rover', 'cat-cars', '{"luxury","lifestyle"}', 'approved'),
('Would you rather have free gas for life or free car maintenance for life?', 'Free gas for life', 'Free car maintenance for life', 'cat-cars', '{"practical","money_minded"}', 'approved'),
('Would you rather drive a manual transmission always or automatic only?', 'Always drive manual', 'Automatic only', 'cat-cars', '{"lifestyle","practical"}', 'approved'),
('Would you rather drive a convertible in summer or a cozy heated car in winter?', 'Convertible in summer', 'Heated car in winter', 'cat-cars', '{"lifestyle","adventurous"}', 'approved'),
('Would you rather have a car that parks itself or a car that never gets stuck in traffic?', 'Car that parks itself', 'Car that avoids all traffic', 'cat-cars', '{"practical","lifestyle"}', 'approved'),
('Would you rather drive across the US in a sports car or in a fully-loaded RV?', 'Sports car road trip', 'Fully-loaded RV road trip', 'cat-cars', '{"adventurous","lifestyle"}', 'approved'),
('Would you rather own a blacked-out luxury car or a bright sports car that turns heads?', 'Blacked-out luxury car', 'Bright sports car that turns heads', 'cat-cars', '{"luxury","lifestyle"}', 'approved'),
('Would you rather drive a classic muscle car or a modern hypercar?', 'Classic muscle car', 'Modern hypercar', 'cat-cars', '{"lifestyle","thrill_seeker"}', 'approved'),
('Would you rather have a car that never needs charging or fueling, or a car that can fly?', 'Never needs fuel or charging', 'Car that can fly', 'cat-cars', '{"practical","thrill_seeker"}', 'approved'),
('Would you rather always have a clean car or always have a fast car?', 'Always clean', 'Always fast', 'cat-cars', '{"lifestyle","thrill_seeker"}', 'approved'),
('Would you rather drive a BMW M3 or a Mercedes-AMG C63?', 'BMW M3', 'Mercedes-AMG C63', 'cat-cars', '{"luxury"}', 'approved'),
('Would you rather own 5 average cars or 1 incredible dream car?', '5 average cars', '1 dream car', 'cat-cars', '{"practical","luxury"}', 'approved'),
('Would you rather always get the closest parking spot or never wait at a red light?', 'Always closest parking', 'Never wait at red lights', 'cat-cars', '{"practical","funny"}', 'approved'),
('Would you rather drive a car with no air conditioning in summer or no heat in winter?', 'No AC in summer', 'No heat in winter', 'cat-cars', '{"practical","thrill_seeker"}', 'approved'),
('Would you rather own a Dodge Challenger or a Ford Mustang?', 'Dodge Challenger', 'Ford Mustang', 'cat-cars', '{"lifestyle","thrill_seeker"}', 'approved'),
('Would you rather have a GPS that is always right or a car stereo that sounds perfect?', 'Always-right GPS', 'Perfect car stereo', 'cat-cars', '{"practical","lifestyle"}', 'approved'),
('Would you rather drive only at night or only during rush hour?', 'Only at night', 'Only during rush hour', 'cat-cars', '{"lifestyle","practical"}', 'approved'),
('Would you rather have a car that always smells amazing or one that''s always spotlessly clean inside?', 'Always smells amazing', 'Always spotlessly clean', 'cat-cars', '{"lifestyle","practical"}', 'approved'),
('Would you rather own a Rolls Royce Ghost or a Bentley Continental GT?', 'Rolls Royce Ghost', 'Bentley Continental GT', 'cat-cars', '{"luxury"}', 'approved'),

-- ============================================================
-- MOVIES & TV (25 questions)
-- ============================================================
('Would you rather watch a movie at home in perfect comfort or at a cinema with the best screen?', 'At home in comfort', 'Cinema with best screen', 'cat-movies', '{"lifestyle","practical"}', 'approved'),
('Would you rather only watch movies from the 90s or only watch movies made after 2015?', 'Only 90s movies', 'Only post-2015 movies', 'cat-movies', '{"lifestyle"}', 'approved'),
('Would you rather binge a whole TV series in one weekend or watch it one episode per week?', 'Binge the whole series', 'One episode per week', 'cat-movies', '{"lifestyle","practical"}', 'approved'),
('Would you rather be in a Marvel movie or a DC movie?', 'Marvel movie', 'DC movie', 'cat-movies', '{"adventurous","lifestyle"}', 'approved'),
('Would you rather know all the spoilers of a movie before you watch it or be completely surprised?', 'Know all the spoilers', 'Complete surprise', 'cat-movies', '{"spontaneous","planner"}', 'approved'),
('Would you rather star in an action movie or a romantic comedy?', 'Action movie', 'Romantic comedy', 'cat-movies', '{"adventurous","romantic"}', 'approved'),
('Would you rather have Netflix forever free or HBO Max forever free?', 'Netflix forever free', 'HBO Max forever free', 'cat-movies', '{"lifestyle","practical"}', 'approved'),
('Would you rather meet the cast of your favorite movie or the director?', 'Meet the cast', 'Meet the director', 'cat-movies', '{"social","career_driven"}', 'approved'),
('Would you rather watch a movie once in theaters or own it forever to watch anytime?', 'Once in theaters', 'Own it forever', 'cat-movies', '{"practical","lifestyle"}', 'approved'),
('Would you rather be in Game of Thrones or Breaking Bad?', 'Game of Thrones', 'Breaking Bad', 'cat-movies', '{"adventurous","thrill_seeker"}', 'approved'),
('Would you rather watch only comedies for a year or only thrillers?', 'Only comedies', 'Only thrillers', 'cat-movies', '{"lifestyle"}', 'approved'),
('Would you rather watch a 3-hour epic film or a tight 90-minute thriller?', '3-hour epic film', '90-minute thriller', 'cat-movies', '{"lifestyle","practical"}', 'approved'),
('Would you rather have a movie based on your life story or write the screenplay for someone else''s life?', 'Movie about my life', 'Write someone else''s screenplay', 'cat-movies', '{"career_driven","lifestyle"}', 'approved'),
('Would you rather watch sports live in person or watch every game from your couch?', 'Live at the stadium', 'Every game from my couch', 'cat-movies', '{"sports","lifestyle"}', 'approved'),
('Would you rather watch The Office again for the first time or finally start a show you''ve been avoiding?', 'Watch The Office fresh again', 'Start that show I''ve avoided', 'cat-movies', '{"lifestyle","spontaneous"}', 'approved'),
('Would you rather live in the world of Harry Potter or Star Wars?', 'Harry Potter world', 'Star Wars world', 'cat-movies', '{"adventurous","lifestyle"}', 'approved'),
('Would you rather have the budget to make any movie or the talent to act in any role?', 'Budget to make any movie', 'Talent to act any role', 'cat-movies', '{"career_driven","creative"}', 'approved'),
('Would you rather watch a movie with subtitles in a language you don''t know or a badly dubbed version?', 'Subtitles in unknown language', 'Badly dubbed version', 'cat-movies', '{"lifestyle","funny"}', 'approved'),
('Would you rather only be able to watch Pixar movies or only Studio Ghibli films?', 'Only Pixar forever', 'Only Studio Ghibli forever', 'cat-movies', '{"lifestyle"}', 'approved'),
('Would you rather be a film critic or a movie director?', 'Film critic', 'Movie director', 'cat-movies', '{"career_driven","lifestyle"}', 'approved'),
('Would you rather watch a horror movie alone at midnight or a romance movie on a first date?', 'Horror alone at midnight', 'Romance on first date', 'cat-movies', '{"thrill_seeker","romantic"}', 'approved'),
('Would you rather watch the Super Bowl live in person or watch it from home with great friends and food?', 'Live at the Super Bowl', 'Home with friends and food', 'cat-movies', '{"sports","social"}', 'approved'),
('Would you rather star in a blockbuster that flops or an indie film that wins an Oscar?', 'Blockbuster that flops', 'Indie film that wins Oscar', 'cat-movies', '{"career_driven","social"}', 'approved'),
('Would you rather have the power to pause real life like you pause Netflix or rewind 30 seconds at any moment?', 'Pause real life', 'Rewind 30 seconds', 'cat-movies', '{"weird","practical"}', 'approved'),
('Would you rather watch every new Marvel movie in theaters or never see another superhero film again?', 'Every new Marvel in theaters', 'Never watch superhero films again', 'cat-movies', '{"lifestyle","adventurous"}', 'approved'),

-- ============================================================
-- SPORTS (25 questions)
-- ============================================================
('Would you rather have LeBron''s basketball skills or Tom Brady''s football skills?', 'LeBron''s basketball skills', 'Tom Brady''s football skills', 'cat-sports', '{"sports","thrill_seeker"}', 'approved'),
('Would you rather attend the Super Bowl or the NBA Finals?', 'The Super Bowl', 'The NBA Finals', 'cat-sports', '{"sports","adventurous"}', 'approved'),
('Would you rather watch the game live at the stadium or in perfect HD at home?', 'Live at the stadium', 'Perfect HD at home', 'cat-sports', '{"sports","practical"}', 'approved'),
('Would you rather run a marathon or complete a triathlon?', 'Run a marathon', 'Complete a triathlon', 'cat-sports', '{"thrill_seeker","adventurous"}', 'approved'),
('Would you rather play in the NFL for 5 years or the NBA for 10 years?', 'NFL for 5 years', 'NBA for 10 years', 'cat-sports', '{"sports","money_minded"}', 'approved'),
('Would you rather be a pro golfer or a pro tennis player?', 'Pro golfer', 'Pro tennis player', 'cat-sports', '{"sports","lifestyle"}', 'approved'),
('Would you rather attend the World Cup final or the Olympic Games opening ceremony?', 'World Cup final', 'Olympic opening ceremony', 'cat-sports', '{"sports","adventurous"}', 'approved'),
('Would you rather be known for winning a championship or being beloved by fans?', 'Win a championship', 'Be beloved by fans', 'cat-sports', '{"sports","social"}', 'approved'),
('Would you rather watch college football or pro football?', 'College football', 'Pro football', 'cat-sports', '{"sports","lifestyle"}', 'approved'),
('Would you rather go skydiving or bungee jumping?', 'Go skydiving', 'Go bungee jumping', 'cat-sports', '{"thrill_seeker","adventurous"}', 'approved'),
('Would you rather have a courtside NBA seat or a 50-yard-line NFL seat?', 'Courtside NBA', '50-yard-line NFL', 'cat-sports', '{"sports","luxury"}', 'approved'),
('Would you rather play golf with Tiger Woods or tennis with Serena Williams?', 'Golf with Tiger Woods', 'Tennis with Serena Williams', 'cat-sports', '{"sports","social"}', 'approved'),
('Would you rather be the fastest runner on earth or the strongest person alive?', 'Fastest runner on earth', 'Strongest person alive', 'cat-sports', '{"thrill_seeker","adventurous"}', 'approved'),
('Would you rather own a professional sports franchise or play on a championship team?', 'Own a sports franchise', 'Play on a championship team', 'cat-sports', '{"sports","money_minded"}', 'approved'),
('Would you rather ski the Alps or surf in Hawaii?', 'Ski the Alps', 'Surf in Hawaii', 'cat-sports', '{"adventurous","thrill_seeker"}', 'approved'),
('Would you rather go to the Masters Golf Tournament or Wimbledon?', 'The Masters', 'Wimbledon', 'cat-sports', '{"sports","luxury"}', 'approved'),
('Would you rather be an Olympic gold medalist or a world champion in a major sport?', 'Olympic gold medalist', 'World champion in major sport', 'cat-sports', '{"sports","career_driven"}', 'approved'),
('Would you rather root for a team that always wins but is boring, or a team that loses a lot but is thrilling?', 'Always wins, boring team', 'Loses a lot but thrilling', 'cat-sports', '{"sports","thrill_seeker"}', 'approved'),
('Would you rather coach a youth sports team or be a personal trainer?', 'Coach youth sports', 'Be a personal trainer', 'cat-sports', '{"career_driven","social"}', 'approved'),
('Would you rather climb Mount Everest or swim the English Channel?', 'Climb Mount Everest', 'Swim the English Channel', 'cat-sports', '{"thrill_seeker","adventurous"}', 'approved'),
('Would you rather be a one-sport legend or a solid multi-sport athlete?', 'One-sport legend', 'Solid multi-sport athlete', 'cat-sports', '{"career_driven","sports"}', 'approved'),
('Would you rather compete in the Daytona 500 or the Indy 500?', 'Daytona 500', 'Indy 500', 'cat-sports', '{"thrill_seeker","cars"}', 'approved'),
('Would you rather do yoga every morning or weight training every morning?', 'Yoga every morning', 'Weight training every morning', 'cat-sports', '{"lifestyle","practical"}', 'approved'),
('Would you rather go deep-sea fishing or fly fishing in a mountain river?', 'Deep-sea fishing', 'Mountain river fly fishing', 'cat-sports', '{"adventurous","lifestyle"}', 'approved'),
('Would you rather have perfect form in every sport or explosive power in every sport?', 'Perfect form in every sport', 'Explosive power in every sport', 'cat-sports', '{"thrill_seeker","sports"}', 'approved'),

-- ============================================================
-- ADVENTURE (20 questions)
-- ============================================================
('Would you rather go off-grid for 30 days in the wilderness or stay in a city you''ve never visited for 30 days?', 'Off-grid for 30 days', 'New city for 30 days', 'cat-adventure', '{"adventurous","thrill_seeker"}', 'approved'),
('Would you rather free solo climb a mountain or base jump from one?', 'Free solo climb', 'Base jump from the top', 'cat-adventure', '{"thrill_seeker","adventurous"}', 'approved'),
('Would you rather spend a night in a haunted house alone or in a submarine underwater?', 'Haunted house alone', 'Submarine underwater', 'cat-adventure', '{"thrill_seeker","weird"}', 'approved'),
('Would you rather go white-water rafting grade 5 or tandem paragliding at 10,000 feet?', 'White-water rafting grade 5', 'Paragliding at 10,000 feet', 'cat-adventure', '{"thrill_seeker","adventurous"}', 'approved'),
('Would you rather trek to Everest Base Camp or sail across the Atlantic Ocean?', 'Trek to Everest Base Camp', 'Sail across the Atlantic', 'cat-adventure', '{"thrill_seeker","adventurous"}', 'approved'),
('Would you rather explore a deep cave system or dive into an underwater cave?', 'Explore a deep cave', 'Dive an underwater cave', 'cat-adventure', '{"thrill_seeker","adventurous"}', 'approved'),
('Would you rather do a 3-day solo survival challenge in the desert or the Amazon jungle?', 'Solo desert survival', 'Amazon jungle survival', 'cat-adventure', '{"thrill_seeker","adventurous"}', 'approved'),
('Would you rather ride an ATV through the Sahara or a snowmobile across Antarctica?', 'ATV through the Sahara', 'Snowmobile across Antarctica', 'cat-adventure', '{"thrill_seeker","adventurous"}', 'approved'),
('Would you rather do a zero-gravity flight or a deep ocean submarine dive?', 'Zero-gravity flight', 'Deep ocean submarine', 'cat-adventure', '{"thrill_seeker","adventurous"}', 'approved'),
('Would you rather swim with whale sharks or dive with hammerhead sharks?', 'Swim with whale sharks', 'Dive with hammerheads', 'cat-adventure', '{"thrill_seeker","adventurous"}', 'approved'),
('Would you rather ride horses across Patagonia or cycle across Vietnam?', 'Horses across Patagonia', 'Cycle across Vietnam', 'cat-adventure', '{"adventurous","thrill_seeker"}', 'approved'),
('Would you rather camp at the Grand Canyon or the Great Barrier Reef?', 'Camp at the Grand Canyon', 'Camp at the Great Barrier Reef', 'cat-adventure', '{"adventurous","lifestyle"}', 'approved'),
('Would you rather spend a week on a deserted island with your best friend or alone but with all amenities?', 'Deserted island with best friend', 'Alone with all amenities', 'cat-adventure', '{"adventurous","social"}', 'approved'),
('Would you rather drive Route 66 in a classic car or bike the Pacific Coast Highway?', 'Drive Route 66', 'Bike the Pacific Coast Highway', 'cat-adventure', '{"adventurous","cars"}', 'approved'),
('Would you rather see a real volcano up close or be inside an active geyser field?', 'Volcano up close', 'Active geyser field', 'cat-adventure', '{"thrill_seeker","adventurous"}', 'approved'),
('Would you rather learn to fly a small plane or sail a yacht?', 'Learn to fly a plane', 'Learn to sail a yacht', 'cat-adventure', '{"thrill_seeker","luxury"}', 'approved'),
('Would you rather run with the bulls in Pamplona or walk across hot coals?', 'Run with the bulls', 'Walk across hot coals', 'cat-adventure', '{"thrill_seeker","weird"}', 'approved'),
('Would you rather spend a night in the Arctic tundra or a night deep in the Congo rainforest?', 'Arctic tundra', 'Congo rainforest', 'cat-adventure', '{"thrill_seeker","adventurous"}', 'approved'),
('Would you rather cliff jump into crystal-clear water or zipline over a rainforest canopy?', 'Cliff jump', 'Zipline over rainforest', 'cat-adventure', '{"thrill_seeker","adventurous"}', 'approved'),
('Would you rather be stranded in the mountains for 48 hours or in the ocean for 24 hours?', 'Mountains for 48 hours', 'Ocean for 24 hours', 'cat-adventure', '{"thrill_seeker","adventurous"}', 'approved'),

-- ============================================================
-- FAMILY (20 questions)
-- ============================================================
('Would you rather raise your kids in a big city or a small town?', 'Big city', 'Small town', 'cat-family', '{"family","practical"}', 'approved'),
('Would you rather have 4 kids or 1 child?', '4 kids', '1 child', 'cat-family', '{"family","lifestyle"}', 'approved'),
('Would you rather your kids have a great public school or sacrifice to send them to private school?', 'Great public school', 'Private school', 'cat-family', '{"family","practical"}', 'approved'),
('Would you rather spend every holiday with your family or travel somewhere new each year?', 'Every holiday with family', 'Travel somewhere new', 'cat-family', '{"family","adventurous"}', 'approved'),
('Would you rather be a stay-at-home parent or a working parent?', 'Stay-at-home parent', 'Working parent', 'cat-family', '{"family","career_driven"}', 'approved'),
('Would you rather know your child will be happy but not wealthy or wealthy but not totally happy?', 'Happy but not wealthy', 'Wealthy but not totally happy', 'cat-family', '{"family","money_minded"}', 'approved'),
('Would you rather live close to your parents or a 5-hour drive away?', 'Close to my parents', '5-hour drive away', 'cat-family', '{"family","lifestyle"}', 'approved'),
('Would you rather your kids be excellent at sports or excellent academically?', 'Excellent at sports', 'Excellent academically', 'cat-family', '{"family","sports"}', 'approved'),
('Would you rather have family dinner together every night or let everyone eat on their own schedule?', 'Family dinner every night', 'Everyone on their own schedule', 'cat-family', '{"family","practical"}', 'approved'),
('Would you rather raise bilingual kids or focus deeply on one language?', 'Raise bilingual kids', 'Focus on one language', 'cat-family', '{"family","practical"}', 'approved'),
('Would you rather have your parents live with you or visit every few months?', 'Parents live with me', 'Visit every few months', 'cat-family', '{"family","lifestyle"}', 'approved'),
('Would you rather start a family business or encourage your kids to pursue their own paths?', 'Family business', 'Their own paths', 'cat-family', '{"family","career_driven"}', 'approved'),
('Would you rather have a family reunion every year or a big family vacation every 5 years?', 'Reunion every year', 'Big vacation every 5 years', 'cat-family', '{"family","travel"}', 'approved'),
('Would you rather teach your kids to be resilient above all else or kind above all else?', 'Resilient above all', 'Kind above all', 'cat-family', '{"family","practical"}', 'approved'),
('Would you rather your child become a doctor or an entrepreneur?', 'Become a doctor', 'Become an entrepreneur', 'cat-family', '{"family","career_driven"}', 'approved'),
('Would you rather have a big loud family or a small tight-knit one?', 'Big loud family', 'Small tight-knit family', 'cat-family', '{"family","social"}', 'approved'),
('Would you rather spend summers with your kids camping or doing city adventures?', 'Camping summers', 'City adventure summers', 'cat-family', '{"family","adventurous"}', 'approved'),
('Would you rather have your family be your biggest supporters or your honest critics?', 'Biggest supporters', 'Honest critics', 'cat-family', '{"family","practical"}', 'approved'),
('Would you rather your kids grow up with social media or without it?', 'With social media', 'Without social media', 'cat-family', '{"family","lifestyle"}', 'approved'),
('Would you rather have siblings or be an only child?', 'Have siblings', 'Be an only child', 'cat-family', '{"family","lifestyle"}', 'approved'),

-- ============================================================
-- FRIENDSHIP (20 questions)
-- ============================================================
('Would you rather have 1 best friend who would do anything for you or 20 good friends?', '1 best friend who does anything', '20 good friends', 'cat-friendship', '{"social","friendship"}', 'approved'),
('Would you rather have friends who are brutally honest or friends who always support you?', 'Brutally honest friends', 'Always supportive friends', 'cat-friendship', '{"social","practical"}', 'approved'),
('Would you rather keep in touch with childhood friends or build deep new friendships as an adult?', 'Keep childhood friends', 'Build new adult friendships', 'cat-friendship', '{"social","lifestyle"}', 'approved'),
('Would you rather have a friend group that challenges you intellectually or one that makes you laugh constantly?', 'Intellectually challenging group', 'Always making me laugh', 'cat-friendship', '{"social","career_driven"}', 'approved'),
('Would you rather be the friend everyone calls when they are in trouble or the one they call to celebrate?', 'Called when in trouble', 'Called to celebrate', 'cat-friendship', '{"social","lifestyle"}', 'approved'),
('Would you rather have friends who live nearby or best friends who are far away?', 'Friends who live nearby', 'Best friends who are far away', 'cat-friendship', '{"social","lifestyle"}', 'approved'),
('Would you rather have a best friend who is wildly successful or one who is deeply content?', 'Wildly successful best friend', 'Deeply content best friend', 'cat-friendship', '{"social","money_minded"}', 'approved'),
('Would you rather lose touch with an old friend gradually or have a dramatic falling out and move on?', 'Gradually lose touch', 'Dramatic falling out', 'cat-friendship', '{"social","practical"}', 'approved'),
('Would you rather have friends who plan everything ahead or ones who are always spontaneous?', 'Always plan ahead', 'Always spontaneous', 'cat-friendship', '{"social","planner"}', 'approved'),
('Would you rather be the friend who always hosts or the one who always shows up?', 'Always the host', 'Always shows up', 'cat-friendship', '{"social","lifestyle"}', 'approved'),
('Would you rather have a friend group that travels together or one that stays local and meets regularly?', 'Travel together', 'Stay local, meet regularly', 'cat-friendship', '{"social","adventurous"}', 'approved'),
('Would you rather have friends from completely different backgrounds than you or friends just like you?', 'Completely different backgrounds', 'Just like me', 'cat-friendship', '{"social","lifestyle"}', 'approved'),
('Would you rather text your friends daily or have rare but meaningful long calls?', 'Text daily', 'Rare meaningful long calls', 'cat-friendship', '{"social","practical"}', 'approved'),
('Would you rather have a best friend who is an introvert or an extrovert?', 'Introvert best friend', 'Extrovert best friend', 'cat-friendship', '{"social","lifestyle"}', 'approved'),
('Would you rather have a work best friend or a home-life best friend?', 'Work best friend', 'Home-life best friend', 'cat-friendship', '{"social","career_driven"}', 'approved'),
('Would you rather attend your friend''s wedding in another country or throw them the best local party?', 'Attend their destination wedding', 'Throw the best local party', 'cat-friendship', '{"social","adventurous"}', 'approved'),
('Would you rather have friends who push you out of your comfort zone or friends who accept your comfort zone?', 'Push me out of comfort zone', 'Accept my comfort zone', 'cat-friendship', '{"social","practical"}', 'approved'),
('Would you rather have a friend you can call at 3am no matter what or a friend who always says the right thing?', 'Call at 3am no matter what', 'Always says the right thing', 'cat-friendship', '{"social","practical"}', 'approved'),
('Would you rather be the funny one in your friend group or the reliable one?', 'The funny one', 'The reliable one', 'cat-friendship', '{"social","lifestyle"}', 'approved'),
('Would you rather have friends who value quality time together or friends who give you space?', 'Value quality time', 'Give me space', 'cat-friendship', '{"social","lifestyle"}', 'approved'),

-- ============================================================
-- LUXURY (20 questions)
-- ============================================================
('Would you rather own a private jet or a mega yacht?', 'Private jet', 'Mega yacht', 'cat-luxury', '{"luxury","money_minded"}', 'approved'),
('Would you rather stay in a $5,000/night hotel suite or use that money on 2 weeks of premium travel?', '$5,000/night hotel suite', '2 weeks premium travel', 'cat-luxury', '{"luxury","adventurous"}', 'approved'),
('Would you rather have a personal chef or a full-time house manager?', 'Personal chef', 'Full-time house manager', 'cat-luxury', '{"luxury","lifestyle"}', 'approved'),
('Would you rather own a Rolex or a Patek Philippe?', 'Rolex', 'Patek Philippe', 'cat-luxury', '{"luxury","money_minded"}', 'approved'),
('Would you rather have front-row seats to every major concert for life or first-class flights forever?', 'Front-row concerts for life', 'First-class flights forever', 'cat-luxury', '{"luxury","lifestyle"}', 'approved'),
('Would you rather wear designer clothes every day or drive a new luxury car every year?', 'Designer clothes every day', 'New luxury car every year', 'cat-luxury', '{"luxury","cars"}', 'approved'),
('Would you rather have a luxury penthouse in Manhattan or a private villa in the south of France?', 'Manhattan penthouse', 'Villa in south of France', 'cat-luxury', '{"luxury","lifestyle"}', 'approved'),
('Would you rather have a walk-in closet the size of a bedroom or a bathroom with a spa?', 'Walk-in closet', 'Spa bathroom', 'cat-luxury', '{"luxury","lifestyle"}', 'approved'),
('Would you rather have a personal stylist or a personal nutritionist?', 'Personal stylist', 'Personal nutritionist', 'cat-luxury', '{"luxury","lifestyle"}', 'approved'),
('Would you rather own an art collection worth $10M or a wine cellar worth $10M?', '$10M art collection', '$10M wine cellar', 'cat-luxury', '{"luxury","money_minded"}', 'approved'),
('Would you rather have a private gym with a personal trainer or a home theater with every movie ever made?', 'Private gym with trainer', 'Home theater, every movie', 'cat-luxury', '{"luxury","lifestyle"}', 'approved'),
('Would you rather fly private to a business meeting or have a chauffeured Rolls Royce?', 'Fly private to meetings', 'Chauffeured Rolls Royce', 'cat-luxury', '{"luxury","career_driven"}', 'approved'),
('Would you rather have a diamond Rolex or a one-of-a-kind piece of jewelry designed just for you?', 'Diamond Rolex', 'Custom one-of-a-kind jewelry', 'cat-luxury', '{"luxury"}', 'approved'),
('Would you rather own a private island or a private mountain chalet?', 'Private island', 'Mountain chalet', 'cat-luxury', '{"luxury","adventurous"}', 'approved'),
('Would you rather spend $50k on one piece of luxury furniture or $50k redecorating your entire home?', '$50k on one luxury piece', '$50k full home redecoration', 'cat-luxury', '{"luxury","practical"}', 'approved'),
('Would you rather have a butler or a personal security team?', 'A butler', 'Personal security team', 'cat-luxury', '{"luxury","lifestyle"}', 'approved'),
('Would you rather own a $500k watch or drive a $500k car?', '$500k watch', '$500k car', 'cat-luxury', '{"luxury","cars"}', 'approved'),
('Would you rather have a box at every NFL game or courtside seats at every NBA game for life?', 'NFL box for life', 'NBA courtside for life', 'cat-luxury', '{"luxury","sports"}', 'approved'),
('Would you rather have a private chef prepare every meal or a nutritionist design your perfect diet?', 'Private chef every meal', 'Nutritionist perfect diet', 'cat-luxury', '{"luxury","foodie"}', 'approved'),
('Would you rather own a $10M mansion and maintain it yourself or live in a $3M smart home fully managed?', '$10M mansion I maintain', '$3M smart home fully managed', 'cat-luxury', '{"luxury","practical"}', 'approved'),

-- ============================================================
-- WEIRD (20 questions)
-- ============================================================
('Would you rather be able to talk to animals or speak every human language?', 'Talk to animals', 'Speak every human language', 'cat-weird', '{"weird","social"}', 'approved'),
('Would you rather know exactly how you will die or know exactly when you will die?', 'Know how I will die', 'Know when I will die', 'cat-weird', '{"weird","practical"}', 'approved'),
('Would you rather have the ability to stop time or turn back time by 10 minutes?', 'Stop time', 'Turn back time 10 minutes', 'cat-weird', '{"weird","practical"}', 'approved'),
('Would you rather be able to fly but only at ground level or teleport but only 10 feet at a time?', 'Fly at ground level', 'Teleport 10 feet at a time', 'cat-weird', '{"weird","funny"}', 'approved'),
('Would you rather always know when someone is lying or be able to make anyone instantly trust you?', 'Always know when lied to', 'Make anyone trust me instantly', 'cat-weird', '{"weird","social"}', 'approved'),
('Would you rather live in the past for a week or visit the future for a day?', 'Live in the past a week', 'Visit the future for a day', 'cat-weird', '{"weird","adventurous"}', 'approved'),
('Would you rather have a photographic memory or be able to speed-read anything instantly?', 'Photographic memory', 'Speed-read anything instantly', 'cat-weird', '{"weird","practical"}', 'approved'),
('Would you rather know the exact number of people who think positively about you or negatively?', 'Who thinks positively', 'Who thinks negatively', 'cat-weird', '{"weird","social"}', 'approved'),
('Would you rather experience your most vivid dream every night or never dream again?', 'Vivid dream every night', 'Never dream again', 'cat-weird', '{"weird","lifestyle"}', 'approved'),
('Would you rather be able to see your own future in a dream or see someone else''s past?', 'See my future', 'See someone else''s past', 'cat-weird', '{"weird","practical"}', 'approved'),
('Would you rather have the ability to heal any disease with your touch or absorb any skill in 1 hour?', 'Heal any disease', 'Absorb any skill in 1 hour', 'cat-weird', '{"weird","practical"}', 'approved'),
('Would you rather be invisible for a day in any location you choose or read one person''s mind for a day?', 'Invisible for a day', 'Read one mind for a day', 'cat-weird', '{"weird","adventurous"}', 'approved'),
('Would you rather your memories be stored on a device and shareable, or fully deleted when recalled?', 'Shareable memory device', 'Deleted when recalled', 'cat-weird', '{"weird","practical"}', 'approved'),
('Would you rather shrink to 4 inches tall for a day or grow to 15 feet tall for a day?', 'Shrink to 4 inches', 'Grow to 15 feet', 'cat-weird', '{"weird","funny"}', 'approved'),
('Would you rather be the only person who can see color or have everyone see colors you describe?', 'Only I see color', 'I describe color to everyone', 'cat-weird', '{"weird","social"}', 'approved'),
('Would you rather discover a new element on the periodic table or discover a new species?', 'Discover a new element', 'Discover a new species', 'cat-weird', '{"weird","adventurous"}', 'approved'),
('Would you rather have the world hear every song stuck in your head or every argument you replay in your mind?', 'Every song in my head', 'Every argument I replay', 'cat-weird', '{"weird","funny"}', 'approved'),
('Would you rather be teleported to a random location on Earth every morning or float 10 feet above ground whenever you stand still?', 'Teleported randomly each morning', 'Float 10 feet when standing still', 'cat-weird', '{"weird","adventurous"}', 'approved'),
('Would you rather always feel slightly cold or always feel slightly warm?', 'Always slightly cold', 'Always slightly warm', 'cat-weird', '{"weird","practical"}', 'approved'),
('Would you rather know the secret of every conspiracy theory or know which famous historical event was faked?', 'Know every conspiracy secret', 'Know which event was faked', 'cat-weird', '{"weird","adventurous"}', 'approved');
